{{- if .Values.infinispan.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cache-config
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
data:
  cache-ispn.xml: |-
{{ .Values.infinispan.nativeConfig | indent 4 }}
{{- end }}
