# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

{{- if and (eq .Values.global.database.location "external") .Values.externalDatabase.ssl (or .Values.externalDatabase.sslCert .Values.externalDatabase.sslKey .Values.externalDatabase.sslRootCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certificates
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.sslCert }}
  sslcert.crt: {{ (.Values.externalDatabase.sslCert | default "# Set sslcert.crt in values.yaml") | b64enc }}
  {{- end -}}
  {{- if .Values.externalDatabase.sslKey }}
  sslkey.pk8: {{ (.Values.externalDatabase.sslKey | default "# Set sslkey.pk8 in values.yaml") | b64enc }}
  {{- end -}}
  {{- if .Values.externalDatabase.sslRootCert }}
  sslrootcert.crt: {{ (.Values.externalDatabase.sslRootCert | default "# Set sslrootcert.crt in values.yaml") | b64enc }}
  {{- end -}}
{{- end -}}
