{{- if eq .Values.prometheus.serviceMonitor.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
          {{- include "common.status-monitor.labels" $ | nindent 4 }}
          {{- include "keycloak.status-monitor.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "keycloak.selector" $ | nindent 4 }}
  ports:
  - name: metrics-http
    port: 9542
    protocol: TCP
    targetPort: {{ .Values.prometheus.port | default 9542 }}
{{- end -}}
